server:
  port: "8080"
  limit_rate: 20
  # 静态文件服务
  # 默认/v1（必填）
  static_prefix: "/v1"

database:
  # 切换数据库驱动
  driver: "sqlite"
  sqlite:
    # SQLite数据库文件路径
    path: "./db/auv.db"
  mysql:
    host: "localhost"
    port: 3306
    user: "auv"
    password: "xBwKba5iFhbszSwK"
    name: "auv"
    ssl_mode: "disable"

admin:
  username: "admin"
  password: "admin123"

user:
  default_password: "123456"

jwt:
  secret: "your_jwt_secret"
  expires_hours: 24
  refresh_window_hours: 1

hitokoto_file: "public/other/hitokoto.txt"